# fpath=($fpath /usr/share/zsh/5.8.1/functions)

# Editors
export EDITOR=e

# Extended globbing is really fun
setopt extendedglob

# Interactive comments are great for recordings, etc.
setopt interactive_comments

# But only with Vim bindings
bindkey -v

# But I still want incremental backwards search
bindkey "^R" history-incremental-pattern-search-backward

# I really, really dislike interrupts
unsetopt beep
unsetopt hist_beep
unsetopt list_beep

# History
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY_TIME

# Adjust path
export PATH=/home/$USER/bin:/home/$USER/.local/bin:$PATH:/snap/bin
export PATH=$PATH:/home/$USER/builds/nim/bin

# Enable colours
autoload -U colors && colors

autoload -Uz compinit
compinit -i

# Nicer prompts
line="$(repeat 1000 echo -n ┈)"
PROMPT="%(?..%F{red}# ┈ %B%?%b%f
)%F{yellow}# ┈%f %D %*%F{yellow} ┈ %f%~%F{yellow} %-2<<$line%<< #%f
"

# Load aliases
test -f ~/.aliases && . ~/.aliases

# Load keys
test -f ~/.keys && . ~/.keys

# Nicer tab completion
zstyle ':completion:*' menu select

# Helper functions
scan() {
    grep -i $1 -r .
}

# Vim editing
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd m edit-command-line


autoload -Uz compinit
compinit -i


export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview' --layout=reverse"

function _print_all_panes() {
  for pane_id in $(tmux list-panes -F '#{pane_id}'); do
    tmux capture-pane -p -J -S 0 -E - -t "$pane_id" | tr ' ' '\n' | sort -u | rg '[a-zA-Z0-9]+'
  done
}

_tmux_pane_words() {
  local current_word="${LBUFFER##* }"
  local new_rbuffer="${RBUFFER/#[^ ]##/}"
  local prompt="${LBUFFER% *} ␣ $new_rbuffer "

  local selected_word=$(_print_all_panes | fzf --query="$current_word" --prompt="$prompt" --height=20 --layout=reverse --no-sort --print-query | tail -n1)
  if [[ -n $selected_word ]]; then
    local new_lbuffer="${LBUFFER% *} $selected_word"
    BUFFER="$new_lbuffer$new_rbuffer"
    CURSOR="${#${new_lbuffer}}"
  fi

  zle redisplay
}

zle -N _tmux_pane_words
bindkey '^U' _tmux_pane_words

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh || true

# Function to interact with claude
function qq {
  /home/knl/dev/qq/qq.sh "$@"
}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/knl/builds/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/knl/builds/miniforge3/etc/profile.d/conda.sh" ]; then
	. "/home/knl/builds/miniforge3/etc/profile.d/conda.sh"
    else
	export PATH="/home/knl/builds/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/knl/builds/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/home/knl/builds/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

export ET_NO_TELEMETRY=1

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# opam configuration
[[ ! -r /home/knl/.opam/opam-init/init.zsh ]] || source /home/knl/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
alias claude="/home/knl/.claude/local/claude"
