# Editors
alias e="emacs -nw"

export EDITOR="/usr/local/bin/emacs -nw"

# But only with Vim bindings
bindkey -v

# But I still want incremental backwards search
bindkey "^R" history-incremental-pattern-search-backward

# I really, really dislike interrupts
unsetopt beep
unsetopt hist_beep
unsetopt list_beep

# History
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY_TIME

# Adjust path
export PATH=/Users/kunalb/bin:$PATH
export PATH=/Users/kunalb/.cargo/bin:$PATH

# Enable colours
autoload -U colors && colors

# Nicer prompts
PROMPT="%{$fg[red]%}%~%{$reset_color%} "

# Load aliases
test -f ~/.aliases && . ~/.aliases

# Load laptop specific settings
test -f ~/.localzshrc && . ~/.localzshrc

# Helper functions
scan() {
    grep -i $1 -r .
}

# Completions
fpath+=~/.zfunc

autoload -Uz compinit
compinit -i
